name: GetVideoM3u8
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 20 * * *'
env:
  TZ: Asia/Shanghai
  
jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
    - uses: actions/checkout@v3
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Running
      run: |
        python -m pip install --upgrade pip
        pip install requests
        python ./main.py
      env:
        BFtoken: ${{ secrets.TOKEN }}
